[package]
name = "spacenav-plus"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Unsafe libspnav FFI bindings for Rust"
repository = "https://github.com/sjkillen/spacenav-plus"
readme = "README.md"
keywords = ["spacemouse", "spacenav"]

[dependencies]
libspnav-bindings = "0.1.0"
#lazy_static = "*"
